import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const GenerateComplaintPDF = (complaint) => {

    const doc = new jsPDF();

    // Title

    doc.setFontSize(20);
    doc.setTextColor(37, 99, 235);
    doc.text(
        "SMART COMPLAINT MANAGEMENT SYSTEM",
        15,
        20
    );

    // Subtitle

    doc.setFontSize(14);
    doc.setTextColor(0, 0, 0);
    doc.text(
        "Complaint Report",
        15,
        32
    );

    // Complaint Details

    autoTable(doc, {

        startY: 40,

        head: [["Field", "Details"]],

        body: [

            [
                "Complaint Number",
                complaint.complaintNumber || "-"
            ],

            [
                "Title",
                complaint.complaintTitle || "-"
            ],

            [
                "Description",
                complaint.complaintDescription || "-"
            ],

            [
                "Category",
                complaint.category || "-"
            ],

            [
                "Status",
                complaint.status || "-"
            ],

            [
                "Citizen Name",
                complaint.citizenName || "-"
            ],

            [
                "Address",
                complaint.address || "-"
            ],

            [
                "District",
                complaint.district || "-"
            ],

            [
                "State",
                complaint.state || "-"
            ],

            [
                "Pincode",
                complaint.pincode || "-"
            ]

        ],

        theme: "grid"

    });

    // Footer

    const finalY = doc.lastAutoTable.finalY + 20;

    doc.setFontSize(11);

    doc.text(
        `Generated On : ${new Date().toLocaleString()}`,
        15,
        finalY
    );

    doc.text(
        "Generated By Smart Complaint Management System",
        15,
        finalY + 10
    );

    // Download PDF

    doc.save(
        `${complaint.complaintNumber}.pdf`
    );

};

export default GenerateComplaintPDF;